version: '3.8'
services:
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    container_name: go-backend

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: svelte-frontend
    depends_on:
      - backend